GROUP_ID=io.alloc.cache
ARTIFACT_ID=common-spring-cache
DESCRIPTION=Spring data redis wrapper Cache Library
URL=https://github.com/mr-alloc/offset-paginator

LICENSE_NAME=The Apache License, Version 2.0
LICENSE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt

DEVELOPER_ID=mr-alloc
DEVELOPER_NAME=mr-alloc
DEVELOPER_EMAIL=mr.allocater@gmail.com

SCM_CONNECTION=scm:git:github.com/mr-alloc/common-spring-cache.git
SCM_DEVELOPER_CONNECTION=scm:git:ssh://github.com:mr-alloc/common-spring-cache.git
SCM_URL=https://github.com/mr-alloc/common-spring-cache